# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
comments:           true

# Setup
title:               Blog de Santiago
tagline:             'Data Analysis, Machine Learning, Big Data'
description:         'Un blog dedicado al Data Analysis, Big Data, Machine Learning, Linux y mucho más'
url:                 http://slarrain.github.io/blog
baseurl:             '/blog'
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Santiago Larrain
  url:               http://santiagolarrain.me
  email:             santiagolarrain@gmail.com
  github:            'https://github.com/slarrain'
  twitter:           'https://twitter.com/slarrain'

# Custom vars
version:             1.0.0

# Tema: Lanyon

gems: [jekyll-paginate]
